name: Deploy to Production
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/entsogBot
            git pull
            
            
            echo "Attempting to stop the old bot..."
            if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
              pkill -15 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
              sleep 10
              if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
                echo "Process did not terminate with SIGTERM, using SIGKILL..."
                pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
                sleep 5
              fi
              if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
                echo "Failed to stop the bot after all attempts."
                exit 1
              else
                echo "Bot stopped successfully."
                exit 0
              fi
            else
              echo "No bot process found, skipping stop."
              exit 0
            fi

            echo "Starting the new bot..."
            ./gradlew build --exclude-task test && ./gradlew --stop
            sleep 5
            nohup java -jar /root/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
            sleep 5
            echo "Bot restarted and running in background. Checking nohup.out for output..."
            cd /root/entsogBot/build/libs
            echo "Deployment successful!"
            exit 0