name: Deploy to Production
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/entsogBot
            git pull
            ./gradlew build --exclude-task test
            sleep 10
            echo "Stopping the old bot..."
            # Останавливаем старый процесс бота
            # pkill -f 'java -jar /***/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar' || true
            pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
            # Даем время для полной остановки
            sleep 10
            
            #nohup java -jar /root/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar &> /dev/null &
            nohup java -jar /root/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &

            echo "Starting the new bot..."
            sleep 5
            cd /root/entsogBot/build/libs        
            echo "Bot restarted successfully!"
            exit 0
            echo "Exit successfully!"