name: Deploy to Production
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/entsogBot
            git pull
            ./gradlew build --exclude-task test
            echo "Stopping the old bot..."
            java -jar exchange_rates_bot-0.0.1-SNAPSHOT.jar & disown
            echo "Starting the new bot..."
            sleep 5
            cd /root/entsogBot/build/libs        
            echo "Bot restarted successfully!"
            exit 0
            echo "Exit successfully!"