name: Deploy to Production
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/entsogBot
            git pull
            ./gradlew build --exclude-task test && ./gradlew --stop
            sleep 10
            echo "Stopping the old bot..."
            if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
              pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
              sleep 5
              if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
                pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
                sleep 5
              fi
            fi
            if ! pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
              echo "Bot stopped successfully."
              exit 0
            else
              echo "Failed to stop the bot after force attempt."
              exit 1
            fi
            echo "Checking if the bot has stopped..."
            attempts=0
            while pgrep -f 'java.*exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; do
              if [ $attempts -ge 5 ]; then
                echo "Failed to stop the bot after 5 attempts."
                exit 1
              fi
              echo "Waiting for the bot to stop..."
              sleep 5
              attempts=$((attempts+1))
            done
            nohup java -jar /root/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
            echo "Bot restarted and running in background. Checking nohup.out for output..."
            echo "Starting the new bot..."
            sleep 5
            cd /root/entsogBot/build/libs        
            echo "Bot restarted successfully!"
            exit 0
            echo "Exit successfully!"